version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: slt_tracker_db
    restart: always
    environment:
      - POSTGRES_USER=slt_admin
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=slt_tracker
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: